title: "Synoptic Edition of Book of the Dead Spell Sources from the 21st Dynasty"
author: "STaTbS21D Project"
description: "STaTbS21D - a Digital Humanities project on Egyptology, provides edited and digitalized Book of the Dead spell sources from the end of the New Kingdom and the beginning of the Third Intermediate Period (particularly the 21st Dynasty) for the Egyptological community and the general public." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "senerpaitui@gmail.com"
twitter_username: "Senerpaitui"
github_username: "STaTbS21D"
#linkedin_username: "linkedinuser"
facebook_username: "STaTbS21D"
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username